on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, synchronize]
  workflow_call:
  workflow_dispatch:

name: ci-build

env:
  DOTNET_VERSION: 8.0.x
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/container-build
        with:
          registry: ghcr.io
          registry-path: ${{ github.repository_owner }}/discord-bot
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          push-image: ${{ github.ref_type == 'branch' && github.ref_protected && github.event_name != 'pull_request' }}